# =============================================================
# PostgreSQL 15 - pg_hba.conf del nodo PRIMARIO
# Alta Disponibilidad SIGO-OLLAS
# =============================================================
# Conexiones locales
local   all             all                                     peer
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Conexiones de la replica (streaming replication)
host    replication     replicator      172.0.0.0/8             scram-sha-256
host    replication     replicator      192.168.0.0/16           scram-sha-256
host    replication     replicator      10.0.0.0/8               scram-sha-256

# Aplicacion SIGO-OLLAS
host    all             app_user        172.0.0.0/8             scram-sha-256
host    all             app_user        192.168.0.0/16           scram-sha-256
host    all             app_user        10.0.0.0/8               scram-sha-256
