# =============================================================
# PostgreSQL 15 - Configuracion del nodo PRIMARIO
# Alta Disponibilidad SIGO-OLLAS
# =============================================================
listen_addresses = '*'
port = 5432
max_connections = 100
shared_buffers = 128MB
dynamic_shared_memory_type = posix

# Replicacion
wal_level = replica
max_wal_senders = 5
max_replication_slots = 3
wal_keep_size = 256MB
hot_standby = on
hot_standby_feedback = on

# WAL Archiving
archive_mode = on
archive_command = 'test ! -f /var/lib/pgsql/15/data/archive/%f && cp %p /var/lib/pgsql/15/data/archive/%f'
archive_timeout = 60

# Logging
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_min_duration_statement = 1000
log_checkpoints = on
log_connections = on
log_disconnections = on
log_line_prefix = '%t [%p]: db=%d,user=%u,app=%a '

# Locale
datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'C.UTF-8'
lc_monetary = 'C.UTF-8'
lc_numeric = 'C.UTF-8'
lc_time = 'C.UTF-8'
